### ISSUE TITLE
Container not starting on CloudRun

### ISSUE THREAD

**Issue by zaremba-tomasz** [nearform/optic#96]
CICD run: https://github.com/nearform/optic/runs/7247791281?check_suite_focus=true

From [logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-07-08T08:06:18.431165Z?project=npm-otp-f6bfc):

```
> optic@1.0.0 start
> node server/index.js

/usr/src/app/server/config.js:7
const pkgDir = require('pkg-dir')

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/pkg-dir/index.js from /usr/src/app/server/config.js not supported.
Instead change the require of index.js in /usr/src/app/server/config.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/src/app/server/config.js:7:16)
    at Object.<anonymous> (/usr/src/app/server/index.js:9:16) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by zaremba-tomasz** [comment]
The problem relates to 6.0.x version of `pkg-dir` where they've moved to be pure ESM module and stopped support CommonJS (https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
